modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/majorfp4/jobscraft/issues"

[[mods]]
modId="jobscraft"
version="${file.jarVersion}"
displayName="JobsCraft"
displayURL="https://github.com/majorfp4/jobscraft"
authors="Major"
description='''
An simple minecraft mod about jobs. 100% IA.
'''

[[dependencies.jobscraft]]
modId="forge"
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="BOTH"

[[dependencies.jobscraft]]
modId="minecraft"
mandatory=true
versionRange="[1.14.4]"
ordering="NONE"
side="BOTH"